FROM clojure:alpine

ENV APP_HOME=/usr/src/app

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
COPY project.clj $APP_HOME
RUN lein do clean, deps
COPY . $APP_HOME
RUN mv "$(lein do test, uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" $APP_HOME/app-standalone.jar
